server:
  port: 9000
spring:
  #服务名称
  application:
    name: gateway-service
    #注册中心nacos的地址
  main:
    web-application-type: reactive  # 网关排除web依赖冲突
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    gateway:
      # 动态路由
      discovery:
        locator:
          enabled: true
      # 自定义路由
#      routes:
#        - id: order_router
#          uri: lb://order-service
#          predicates:
#            - Path=/order-service/**
#          filters:
#            - StripPrefix=1
  redis:
    port: 6379            # 服务器端口
    host: localhost       # r服务器地址
    database: 0           # 数据库索引（默认0）
    jedis:
      pool:
        max-active: 50      # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20        # 连接池中的最大空闲连接数
        min-idle: 2         # 连接池中的最小空闲连接数
    timeout: 5000ms # 连接超时时间（毫秒）